spring:
  application:
    name: guestbook
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://np.me92100984.com:3306/guestbook
    username: guestbook
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  thymeleaf:
    cache: false
  
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - templates
# server:
#   servlet:
#     context-path: /guestbook
  
      